sudo: false
language: php
dist: trusty
php: 5.6
matrix:
  fast_finish: true
env:
  global:
  - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
  - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
  - BUILD_DIR=$TRAVIS_BUILD_DIR
jdk:
- oraclejdk8
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - vendor
addons:
  chrome: stable
notifications:
  slack:
    rooms:
      secure: HmW+cXj8SKKiSq7B/bR0LgmF3ne7Ur2len2vb+A4w4cA03gueP4cjKFZR1jBf9shUnMsnGO2Sdpq9s6KQHrtTuuo4wKq4P8XKp5FHFz9YqIDDlQl9XQxs1BhjD3VOlar/Zzv30ZXm3Y8gd6Fbqt0/b3DPmMfv5SGVxLWUqKhQD0BOuCNhfylToAU8iBQ8mW77PQRQjnGk8SzcObheREU3aqHVK9M7+eFm9m4ucsTLiXURCdwgDASraQyBMawLeWyw1Lk+YJMSQ3wg7cU4Q9SgwBtyaXJCNte/+h4rhFk33+N3653Hwee20CSxj+9bogpEMhMsi9O/O30L858N38Sat3bLZBxqDI7EACU3lj1feqya7KjkyFAZEI/yIObnIshFqj+Q6sIYoaJgDmYk+9gCcBlRT3lW7f30OKSLXtDbUNKmEDtMRNTsuSr8OSGDk4iny56XY6Ij2i9ZO29i9Hdp92qZZCjfrqg6FRoTEmgR1hMcCHRbfqiIVqAm+TShlq0qERo1o9BdROVWTZeZ3nHGz4WS5A5iba1LFanG0shvUebsepXnlIYxK0EXzbNqes+ZqI6lL/j1MF8gzBOhQtsLlRuX5FxtO1tqZysJXjyh89HAZ6ookLv5c1BvHLfkjmldoagvNOpv+pdlIp/3xILRlUf6NGnE0jaX4IwUEs16pY=
before_install:
- ssh-keyscan -p 2974 -t rsa,dsa,ecdsa,ED25519 -H www.chm-cbd.net 2>&1 | tee -a $HOME/.ssh/known_hosts
- ssh-keyscan -t rsa,dsa,ecdsa,ED25519 -H gitlab.com 2>&1 | tee -a $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_e95f2b9cea18_key -iv $encrypted_e95f2b9cea18_iv
  -in travis_deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
- phpenv config-rm xdebug.ini
- composer self-update
- composer validate --no-check-all --ansi
- composer install
- source ${BLT_DIR}/scripts/travis/exit_early
install:
- source ${BLT_DIR}/scripts/travis/setup_environment
- source ${BLT_DIR}/scripts/travis/setup_project
script:
- source ${BLT_DIR}/scripts/travis/run_tests
deploy:
- provider: script
  script: "${BLT_DIR}/scripts/travis/deploy_branch"
  skip_cleanup: true
  on:
    branch: develop
    php: 5.6
- provider: script
  script: "${BLT_DIR}/scripts/travis/deploy_branch"
  skip_cleanup: true
  on:
    branch: master
    php: 5.6
#- provider: script
#  script: "${BLT_DIR}/scripts/travis/deploy_tag"
#  skip_cleanup: true
#  on:
#    tags: true
#    php: 5.6
