project:
  machine_name: boilerplate
  prefix: boilerplate
  human_name: 'Boilerplate 8'
  profile:
    name: standard
  local:
    protocol: http
    hostname: '${project.machine_name}.local'
git:
  default_branch: develop
  remotes:
    - 'git@github.com:cristiroma/drupal.boilerplate.8.git'
  user:
    name: cristiroma
    email: ci@no-reply.org
drush:
  aliases:
    remote: '${project.machine_name}.prod'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: {  }
    uninstall: {  }
  ci:
    enable: {  }
    uninstall: [shield, seckit]
  dev:
    enable: [shield, shield]
    uninstall: {  }
  test:
    enable: [shield, shield]
    uninstall: {  }
  prod:
    enable: {  }
    uninstall: {  }
setup:
  strategy: sync
target-hooks:
  frontend-setup:
    dir: '${docroot}/themes/custom/boilerplate'
    command: 'npm install'
  frontend-build:
    dir: '${docroot}/themes/custom/boilerplate'
    command: 'npm run build'
