project:
  machine_name: boilerplate
  prefix: boilerplate
  human_name: Boilerplate 8
  profile:
    name: standard
  local:
    protocol: http
    hostname: '${project.machine_name}.local'
git:
  default_branch: develop
  remotes:
    - 'git@github.com:cristiroma/drupal.boilerplate.8.git'
  user:
    name: cristiroma
    email: ci@no-reply.org
setup:
  strategy: sync
drush:
  aliases:
    remote: '${project.machine_name}.prod'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    # Extra stuff from development split.
    enable: []
    uninstall: []
  ci:
    # Extra stuff from development split.
    enable: {  }
    uninstall: [shield, seckit]
  dev:
    # Extra stuff from development split.
    enable: [shield]
    uninstall: { }
  test:
    # Extra stuff from development split.
    enable: [shield]
    uninstall: { }
  prod:
    # Extra stuff from prod split.
    enable: { }
    uninstall: { }

target-hooks:
  frontend-setup:
   dir: ${docroot}/themes/custom/boilerplate
   command: 'npm install'
  frontend-build:
   dir: ${docroot}/themes/custom/boilerplate
   command: 'npm run build'
